-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, 
        SUM(CASE WHEN A.STATUS = 'DONE' THEN A.PRICE ELSE 0 END) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID=B.USER_ID
GROUP BY B.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES