SELECT 
    CASE 
        WHEN (D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%'))
            AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Python%') THEN 'A'
        WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#%') THEN 'B'
        WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') THEN 'C'
        ELSE NULL
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS D
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
